# This workflow runs checks every 6 hours for package versions that
# can be deleted using https://github.com/stripethree/gpr-janitor

on:
  schedule:
    - cron: "5 */6 * * *"

jobs:
  package-cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: stripethree/gpr-janitor@v1
        with:
          dry-run: false
          keep-versions: 6
          min-age-days: 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
